# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('homepage', models.CharField(max_length=120)),
                ('image', models.CharField(max_length=120)),
                ('short_summary', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=400)),
            ],
        ),
    ]
