# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170423_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingModel',
            new_name='ReviewModel',
        ),
    ]
