# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170423_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseratingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=200)),
            ],
        ),
    ]
