# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_courseratingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
        migrations.AddField(
            model_name='courseratingmodel',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='course.CourseModel'),
        ),
        migrations.AddField(
            model_name='courseratingmodel',
            name='user',
            field=models.ForeignKey(default='moorthy', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
