# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20170423_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseratingModel',
            new_name='CoursereviewModel',
        ),
    ]
