# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_auto_20170423_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursereviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=200)),
                ('course', models.ManyToManyField(blank=True, null=True, to='course.CourseModel')),
                ('user', models.ForeignKey(default='moorthy', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
